### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by prodkid** [copygirl/BetterStorage#293] opened 2015-06-23 06:14 UTC
Rolled back a grief a player caused, ending up corrupting that area. 

Reports:
http://pastebin.com/ebXyvr4G
http://pastebin.com/i9KFACyA

**Comment by prodkid** [comment] 2015-06-23 06:17
Was able to remove the entity, but thought it would be nice to show those errors.

**Comment by copygirl** [comment] 2015-06-23 08:34
What did you use to roll back?

**Comment by prodkid** [comment] 2015-06-23 11:44
hawkeye

**Comment by copygirl** [comment] 2015-06-23 18:33
Does it not restore tile entity data? What happens to contents of chests? Seaching for "BlockState" quickly, it's *supposed* to contain tile entity data ...

I know, as a user, corrupted areas / worlds can be really annoying, but ever since this has first been reported, I've not wanted to "fix" it. Because either I didn't know what caused it, or the cause was another mod.

**Comment by prodkid** [comment] 2015-06-24 00:15
I was unable to view the contents of the chests. Had to remove it to prevent the crashing.

**Comment by copygirl** [comment] 2015-06-26 00:09
[bob71 has responded to the issue above.](https://github.com/bob7l/HawkReloaded/issues/45#issuecomment-115422840)

Guess I'll close the issue for now. Like I explained above, it's not something I'd want to "fix". Thanks for reporting it though!

**Closed by copygirl** 2015-06-26 00:09 UTC
Labels: bug, crossmod, investigate
