### ISSUE TITLE
Backpack drops as item not as block

### ISSUE THREAD

**Issue by AveoCross** [copygirl/BetterStorage#322] opened 2017-01-23 17:23 UTC
Hi! I know this mod won't be have any more releases but I added BetterStorage to my modpack anyway. 
I just found bug with dropBackpackOnDeath=true. I also have GraveStone Mod which generates gravestones on death. If backpack is empty, gravestone and backpack are generated as blocks. But if backpack has any item in it, then backpack is dropped from player as normal item and gravestone can't catch it. 
Is any solution for this? Maybe some config change?

**Comment by copygirl** [comment] 2017-01-23 19:48
Closed as duplicate of #288. Guess I never got around to do that. Sorry.

The fix would likely involve moving the backpack dropping to `PlayerDropsEvent` for players and use `LivingDeathEvent` for every non-player entity. (Something to do for Wearable Backpacks as well.) Won't implement the fix for BetterStorage myself though, as I've abandoned this mod.

**Closed by copygirl** 2017-01-23 19:48 UTC
Labels: crossmod, duplicate
